### ISSUE TITLE
TF Lite binaries 2.5.0 install problems

### ISSUE THREAD

**Issue by CaptainDario** [am15h/tflite_flutter_plugin#129]
After running the new version of the install script and building my applications I encounter:
```
C:\Users\dario\AppData\Local\Android\sdk\ndk\21.1.6352462\toolchains\llvm\prebuilt\windows-x86_64\bin\llvm-strip.exe: error: 'E:\projects\DaKanjiRecognizerMobile\da_kanji_mobile\build\app\intermediates\merged_native_libs\debug\out\lib\x86\libtensorflowlite_c.so': The file was not recognized as a valid object file
```

While running inference I encounter than:
```
E/flutter ( 6835): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libtensorflowlite_c.so': dlopen failed: "/data/app/~~zJpFAe-GigvCj5nJKt3QbA==/com.DaAppLab.DaKanjiRecognizer-8_T4y9MbmL-_03CK1qt54w==/lib/x86/libtensorflowlite_c.so" is too small to be an ELF executable: only found 9 bytes
E/flutter ( 6835): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
E/flutter ( 6835): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
E/flutter ( 6835): #2      tflitelib.<anonymous closure> (package:tflite_flutter/src/bindings/dlib.dart:8:27)
E/flutter ( 6835): #3      tflitelib (package:tflite_flutter/src/bindings/dlib.dart:14:2)
E/flutter ( 6835): #4      tflitelib (package:tflite_flutter/src/bindings/dlib.dart)
E/flutter ( 6835): #5      tfLiteInterpreterOptionsCreate (package:tflite_flutter/src/bindings/interpreter_options.dart:10:5)
E/flutter ( 6835): #6      tfLiteInterpreterOptionsCreate (package:tflite_flutter/src/bindings/interpreter_options.dart)
E/flutter ( 6835): #7      new InterpreterOptions (package:tflite_flutter/src/interpreter_options.dart:22:28)
E/flutter ( 6835): #8      DrawingInterpreter._cpuInterpreter (package:da_kanji_mobile/model/core/DrawingInterpreter.dart:336:21)
E/flutter ( 6835): #9      DrawingInterpreter._initInterpreterAndroid (package:da_kanji_mobile/model/core/DrawingInterpreter.dart:268:27)
E/flutter ( 6835): <asynchronous suspension>
E/flutter ( 6835): #10     DrawingInterpreter.init (package:da_kanji_mobile/model/core/DrawingInterpreter.dart:109:22)
E/flutter ( 6835): <asynchronous suspension>
E/flutter ( 6835):
```

**Comment by CaptainDario** [comment]
Seems to be realted to the install script.
After downloading the libraries from the release page and copying them to: `android\app\src\main\jniLibs\x86_64` and `android\app\src\main\jniLibs\x86`, everything works.

**Comment by am15h** [comment]
Hi @CaptainDario, I just patched the install script for windows, can you check if it works?

**Comment by CaptainDario** [comment]
Thanks for your quick help!
It is working now.
