### ISSUE TITLE
Invalid input data

### ISSUE THREAD

**Issue by quochuynh67** [am15h/tflite_flutter_plugin#133]
Hi, I am using posenet_mobilenet_v1_100_257x257_multi_kpt_stripped.tflit. but I don't know the input data size. The console log here

E/tflite  (27994): tensorflow/lite/kernels/conv.cc:316 input->dims->size != 4 (1 != 4)
E/tflite  (27994): Node number 0 (CONV_2D) failed to prepare.
E/flutter (27994): [ERROR:flutter/runtime/dart_isolate.cc(1137)] Unhandled exception:
E/flutter (27994): Bad state: failed precondition
E/flutter (27994): #0      checkState (package:quiver/check.dart:74:5)
E/flutter (27994): #1      Interpreter.allocateTensors (package:tflite_flutter/src/interpreter.dart:142:5)
E/flutter (27994): #2      Interpreter.runForMultipleInputs (package:tflite_flutter/src/interpreter.dart:180:7)
E/flutter (27994): #3      Interpreter.run (package:tflite_flutter/src/interpreter.dart:157:5)
E/flutter (27994): #4      Classifier.predict (package:flutter_pose_dance/classifier.dart:108:19)
E/flutter (27994): #5      IsolateUtils.entryPoint (package:flutter_pose_dance/isolate_utils.dart:46:52)
E/flutter (27994): <asynchronous suspension>

Could you recommend for me the document or the way to fix it? Thank you so much!

**Comment by quochuynh67** [comment]
@am15h

**Comment by quochuynh67** [comment]
When I check the code

inputTensors = getInputTensors();
    for (int i = 0; i < inputs.length; i++) {
      inputTensors.elementAt(i).setTo(inputs[i]);
    }
}    
    
 void setTo(Object src) {
    Uint8List bytes = _convertObjectToBytes(src);
    int size = bytes.length;
    final ptr = calloc<Uint8>(size);
    checkState(isNotNull(ptr), message: 'unallocated');
    final externalTypedData = ptr.asTypedList(size);
    externalTypedData.setRange(0, bytes.length, bytes);
    checkState(tfLiteTensorCopyFromBuffer(_tensor, ptr.cast(), bytes.length) == // Error happen because this line
        TfLiteStatus.ok);
    calloc.free(ptr);
  }

**Comment by bazinac** [comment]
I am having the same issue with my Mobilenet classifier. @quochuynh67, have you managed to solve this somehow please?

**Comment by hamidrezabstn** [comment]
hi 
i have same issue

**Comment by tahesse** [comment]
I have the same issue. I found that the `tfLiteTensorCopyFromBuffer(_tensor, ptr.cast(), bytes.length)` produces the error `type 'Pointer<NativeType>' is not a subtype of type 'Pointer<Void>'`.
If I modify the code as follows

    tfLiteTensorCopyFromBuffer(_tensor, ptr.cast<Void>(), bytes.length)

it does not produce the error anymore but merely the return code `1`.
@am15h I am not sure if this is some error with dart:ffi because this issue is my first encounter with dart:ffi. Maybe you know more on this issue?

Let me know if I shall provide my code + image.

**Comment by tahesse** [comment]
For anyone struggling with this issue; see my previous post on how to debug the mismatch leading to the `Bad state: failed precondition`.
Apparently, I forgot to convert the image to grayscale. I had to copy all the code from tflite_flutter_helper package into my code because it was not exported. PR pending: https://github.com/am15h/tflite_flutter_helper/pull/54/files

The grayscale conversion of the image package did not work in this case.
