### ISSUE TITLE
Android 12(Api Level 31): TfLiteGpuDelegate Invoke: GpuDelegate must run on the same thread where it was initialized.

### ISSUE THREAD

**Issue by bolotkalil** [am15h/tflite_flutter_plugin#184]
Hi, Guys. 
After upgrade my android os to version 12, I use latest version of this plugin and I launch tflite in isolation. 

It throws this error:
`TfLiteGpuDelegate Invoke: GpuDelegate must run on the same thread where it was initialized.`
`E/tflite  (20055): Node number 64 (TfLiteGpuDelegateV2) failed to invoke.`
`E/flutter (20055): [ERROR:flutter/runtime/dart_isolate.cc(1111)] Unhandled exception:`
`E/flutter (20055): Bad state: failed precondition`
`E/flutter (20055): #0      checkState (package:quiver/check.dart:74:5)`
`E/flutter (20055): #1      Interpreter.invoke (package:tflite_flutter/src/interpreter.dart:150:5)`
`E/flutter (20055): #2      Interpreter.runForMultipleInputs (package:tflite_flutter/src/interpreter.dart:190:5)`
`E/flutter (20055): #3      Classifier.predict (package:myai/ai/tflite/mobilenet/object/classifier.dart:179:19)`
`E/flutter (20055): #4      IsolateHelper.entryPoint (package:myai/ai/helper/isolate_helper.dart:51:30)`

My code:
`final gpuDelegateV2 = GpuDelegateV2(`
`    options: GpuDelegateOptionsV2(`
`      isPrecisionLossAllowed:true,`
`      inferencePreference:TfLiteGpuInferenceUsage.preferenceSustainSpeed,`
`     inferencePriority1:TfLiteGpuInferencePriority.minMemoryUsage,`
`      inferencePriority2:TfLiteGpuInferencePriority.auto,`
`      inferencePriority3:TfLiteGpuInferencePriority.auto,`
`    )`
`);`
`var interpreterOptions = InterpreterOptions()..addDelegate(gpuDelegateV2);`
`_interpreter = interpreter ??`
 `   await Interpreter.fromAsset(`
 `       MODEL_FILE_NAME,`
`        options: interpreterOptions`
`    );`

Anyone faced such problem? Any suggestions how to fix it?

**Comment by tahesse** [comment]
Haven't tried the GpuDelegate yet but it sounds like some issue related to isolates. Isolates in flutter cannot communicate with one another, i.e. they are stateless. If you launch your inference in an isolate different from the main thread, it won't have access to the GpuDelegate.
Either you register the delegate with the other [inference] isolate or try to establish communication towards the GpuDelegate on the main thread (probably hard). There exists this plugin for communication between isolates: https://pub.dev/packages/isolate_handler
Good luck!

**Comment by tahesse** [comment]
> @tahesse  Thanks for your reply. I fixed it, I reduced the target sdk version to older version, it works fine, on the latest version does not work. I used isolates but on new version it requires the instances of tensorflow and app should be in same thread. What do you think on new Android 12 is it bug or not?

Tbf, I haven't tested it with the newest version. At this point, I'm not sure if the library is still maintained.

**Comment by uayo002** [comment]
Has someone solved the problem?
TfLiteGpuDelegate does not work for me in Android 12, in previous versions it works fine for me, the problem is that Google Play will require that apps target API level 31 (Android 12) or higher.
