### ISSUE TITLE
MacOS Incorrectly read static libraries with .so suffix

### ISSUE THREAD

**Issue by ash0080** [am15h/tflite_flutter_plugin#199]
https://github.com/am15h/tflite_flutter_plugin/blob/659e6d5fbf95506f89cf487ae3e355dd4ff7bc2a/lib/src/bindings/dlib.dart#:~:text=%27mac%27%3B-,ext,-%3D%20%27so%27

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library '~/Library/Containers/com.example.dogCat/Data/blobs/libtensorflowlite_c-mac.so': dlopen(~/Library/Containers/com.example.dogCat/Data/blobs/libtensorflowlite_c-mac.so, 0x0001): tried: '~/Library/Containers/com.example.dogCat/Data/blobs/libtensorflowlite_c-mac.so' (no such file)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      tflitelib.<anonymous closure> (package:tflite_flutter/src/bindings/dlib.dart:39:27)
#3      tflitelib (package:tflite_flutter/src/bindings/dlib.dart:41:2)
#4      tflitelib (package:tflite_flutter/src/bindings/dlib.dart)
#5      tfLiteModelCreateFromBuffer (package:tflite_flutter/src/bindings/model.dart:10:35)
#6      tfLiteModelCreateFromBuffer (package:tflite_flutter/src/bindings/model.dart)
#7      new Model.fromBuffer (package:tflite_flutter/src/model.dart:36:19)

```

**Comment by ash0080** [comment]
also, blobs/ is not packaged in build https://github.com/am15h/tflite_flutter_plugin/issues/181

**Comment by CaptainDario** [comment]
@ash0080 I have a fix for this and will open a pull request soon.

**Comment by walsha2** [comment]
@CaptainDario any update on this?

@ash0080 do you have a workaround? Just modify the source or is the `blob` packaging issue in #181 still a blocker?

**Comment by CaptainDario** [comment]
@walsha2 I found a way to make it work and forgot to open the PR.

I will take a look what I did and update here. Because nobody will merge the PR anyways.

**Comment by walsha2** [comment]
@CaptainDario I actually got this to work by forking. First, the change to `dlib.dart` noted above is def a typo.

The `else if (Platform.isMacOS)` line should be the following. I can open an PR for that.

```git
ext = 'dylib';
```

Second, #181 is also a problem and the easier way to "resolve" that in the interim was to simply copy the files manually into the expected location. This should be part of the build step as you noted in #181

```
cd <PROJECT ROOT>
cp -r blobs/ <PROJECT ROOT>/build/macos/Build/Products/Debug/flutter.app/Contents/MacOS/blobs
```

----------

The second part is not a real solution, so if you have an actually solution please do open a PR and note it in #181.

Regarding this plugin, this is my first time using it, but it looks super useful and worked great for my use case. The code traffic seems like it has stagnated. Is this package still maintained? 

FYI @am15h - please feel free to chime in. Thanks!

**Comment by CaptainDario** [comment]
@walsha2 take a look at [my fork](https://github.com/CaptainDario/DaKanji/blob/main/plugins/tflite_flutter_plugin/lib/src/bindings/dlib.dart).
For MacOS you need to add the dynamic library in Xcode to your project's resources. This will lead to the library being available 
``` dart
Directory(Platform.resolvedExecutable).parent.parent.path + '/resources/libtensorflowlite_c-mac.dylib'
```

For Linux and Windows you need to adapt the CMakeLists.txt (of *your* project *not* TF Lite plugin), at the end add (my project [windows](https://github.com/CaptainDario/DaKanji/blob/690d3bac916713abd592a27936a080bf14408a73/windows/CMakeLists.txt#L97) and [lin](https://github.com/CaptainDario/DaKanji/blob/main/linux/CMakeLists.txt#L118))

``` CMake
install(
  FILES ${PROJECT_BUILD_DIR}/../blobs/libtensorflowlite_c-win.dll 
  DESTINATION ${INSTALL_BUNDLE_DATA_DIR}/../blobs/
)
```

this will result in the lib being available in the blobs folder. However, this solution is outside of this plugin that's, why I didn't open a PR. I think there is a way to include the blobs in a better way...

I am following this repo already for ~1 1/2 years and there is nearly no activity, so do not expect an answer from the author.
However, if this repo gains traction again, there are quite a few ways to make this more user-friendly. For example, I adapted this package so it auto downloads the libs on iOS / Android. If you are interested take a look at [my fork](https://github.com/CaptainDario/DaKanji/tree/main/plugins/tflite_flutter_plugin).

**Comment by walsha2** [comment]
> ...so do not expect an answer from the author

Well that's sad to hear. Thanks for following up, I will definitely take a look at your fork. Hopefully we can revive this plugin, or at least get the maintainers to open it up to other people to maintain. 

@am15h is that something we can do? It is 100% understandable if the original maintainers no longer have the time to support the plugin. Can we open the package to other maintainers? [tflite_flutter](https://pub.dev/packages/tflite_flutter) already has 250+ likes on pub.dev. It would be better to keep this package up to date rather than create clones with similar names and confuse users.

**Comment by wownsdl13** [comment]
> @walsha2 take a look at [my fork](https://github.com/CaptainDario/DaKanji/blob/main/plugins/tflite_flutter_plugin/lib/src/bindings/dlib.dart). For MacOS you need to add the dynamic library in Xcode to your project's resources. This will lead to the library being available
> 
> ```dart
> Directory(Platform.resolvedExecutable).parent.parent.path + '/resources/libtensorflowlite_c-mac.dylib'
> ```
> 
> For Linux and Windows you need to adapt the CMakeLists.txt (of _your_ project _not_ TF Lite plugin), at the end add (my project [windows](https://github.com/CaptainDario/DaKanji/blob/690d3bac916713abd592a27936a080bf14408a73/windows/CMakeLists.txt#L97) and [lin](https://github.com/CaptainDario/DaKanji/blob/main/linux/CMakeLists.txt#L118))
> 
> ```cmake
> install(
>   FILES ${PROJECT_BUILD_DIR}/../blobs/libtensorflowlite_c-win.dll 
>   DESTINATION ${INSTALL_BUNDLE_DATA_DIR}/../blobs/
> )
> ```
> 
> this will result in the lib being available in the blobs folder. However, this solution is outside of this plugin that's, why I didn't open a PR. I think there is a way to include the blobs-dir in a better way...
> 
> I am following this repo already for ~1 1/2 years and there is nearly no activity, so do not expect an answer from the author. However, if this repo gains traction again, there are quite a few ways to make this more user-friendly. For example, I adapted this package so it auto downloads the libs on iOS / Android. If you are interested take a look at [my fork](https://github.com/CaptainDario/DaKanji/tree/main/plugins/tflite_flutter_plugin).



> @walsha2 take a look at [my fork](https://github.com/CaptainDario/DaKanji/blob/main/plugins/tflite_flutter_plugin/lib/src/bindings/dlib.dart). For MacOS you need to add the dynamic library in Xcode to your project's resources. This will lead to the library being available
> 
> ```dart
> Directory(Platform.resolvedExecutable).parent.parent.path + '/resources/libtensorflowlite_c-mac.dylib'
> ```
> 
> For Linux and Windows you need to adapt the CMakeLists.txt (of _your_ project _not_ TF Lite plugin), at the end add (my project [windows](https://github.com/CaptainDario/DaKanji/blob/690d3bac916713abd592a27936a080bf14408a73/windows/CMakeLists.txt#L97) and [lin](https://github.com/CaptainDario/DaKanji/blob/main/linux/CMakeLists.txt#L118))
> 
> ```cmake
> install(
>   FILES ${PROJECT_BUILD_DIR}/../blobs/libtensorflowlite_c-win.dll 
>   DESTINATION ${INSTALL_BUNDLE_DATA_DIR}/../blobs/
> )
> ```
> 
> this will result in the lib being available in the blobs folder. However, this solution is outside of this plugin that's, why I didn't open a PR. I think there is a way to include the blobs-dir in a better way...
> 
> I am following this repo already for ~1 1/2 years and there is nearly no activity, so do not expect an answer from the author. However, if this repo gains traction again, there are quite a few ways to make this more user-friendly. For example, I adapted this package so it auto downloads the libs on iOS / Android. If you are interested take a look at [my fork](https://github.com/CaptainDario/DaKanji/tree/main/plugins/tflite_flutter_plugin).



<img width="348" alt="Screenshot 2023-03-07 at 12 20 51 AM" src="https://user-images.githubusercontent.com/16278142/223152912-cc49a9b6-c35c-4bf6-bbec-24b614effea3.png">

upload to resources folder means like this??? could you please describe this more in detail???

I'm struggling with this now.. :(
