### ISSUE TITLE
Unhandled Exception: Exception: FormatException: Missing extension byte (at offset 2610)

### ISSUE THREAD

**Issue by farazk86** [am15h/tflite_flutter_plugin#40]
Hi,

I am getting above error during my ``loadModel()`` block. Here is the full error stack:

```
I/flutter (21928): Interpreter Created Successfully
I/flutter (21928): input_shape:
I/flutter (21928): [1, 224, 224, 3]
I/flutter (21928): TfLiteType.uint8
I/flutter (21928): output_shape:
I/flutter (21928): [1, 965]
I/flutter (21928): output_type:
I/flutter (21928): TfLiteType.uint8
E/flutter (21928): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Exception: FormatException: Missing extension byte (at offset 2610)
E/flutter (21928): #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1783:7)
E/flutter (21928): #1      Utf8Decoder.convert (dart:convert/utf.dart:321:42)
E/flutter (21928): #2      Utf8Codec.decode (dart:convert/utf.dart:62:20)
E/flutter (21928): #3      AssetBundle._utf8decode (package:flutter/src/services/asset_bundle.dart:81:17)
E/flutter (21928): #4      _IsolateConfiguration.apply (package:flutter/src/foundation/_isolates_io.dart:83:34)
E/flutter (21928): #5      _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:90:65)
E/flutter (21928): #6      Timeline.timeSync (dart:developer/timeline.dart:163:22)
E/flutter (21928): #7      _spawn (package:flutter/src/foundation/_isolates_io.dart:87:35)
E/flutter (21928): #8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:304:17)
E/flutter (21928): #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (21928): 
```

And below is my code:

```dart
class _HomeState extends State<Home> {
  Interpreter interpreter;
  List<int> _inputShape;
  List<int> _outputShape;
  TfLiteType _outputType = TfLiteType.uint8;
  TensorImage _inputImageTensor;
  TensorBuffer _outputBuffer;
  List<String> labels;
  final int _labelsLength = 965;
  final String _labelsFileName = 'assets/aiy_birds_V1_labelmap.txt';
  String modelName = 'aiy_vision_birds.tflite';

  bool _predicting = false;
  final picker = ImagePicker();
  File _imageFile;
  Category category;

  @override
  void initState(){
    super.initState();
    loadStuff();
  }

  loadStuff() async{
    await loadModel();
    await loadLabels();
  }

  Future<void> loadModel() async {
    try {
      interpreter = await Interpreter.fromAsset(modelName);
      print('Interpreter Created Successfully');

      _inputShape = interpreter.getInputTensor(0).shape;
      print('input_shape:');
      print(_inputShape);
      print(interpreter.getInputTensor(0).type);
      _outputShape = interpreter.getOutputTensor(0).shape;
      print('output_shape:');
      print(_outputShape);
      _outputType = interpreter.getOutputTensor(0).type;
      print('output_type:');
      print(_outputType);

      _outputBuffer = TensorBuffer.createFixedSize(_outputShape, _outputType);

    } catch (e) {
      print('Unable to create interpreter, Caught Exception: ${e.toString()}');
    }
  }
```

I have also run the required ``install.bat`` the output of which is below:

```
C:\AndroidStudioProjects\flutter_app_tfliter>install.bat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   652  100   652    0     0    652      0  0:00:01 --:--:--  0:00:01  1605
100 1270k  100 1270k    0     0  1270k      0  0:00:01  0:00:01 --:--:-- 1270k
        1 file(s) moved.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   654  100   654    0     0    654      0  0:00:01 --:--:--  0:00:01  1901
100 1843k  100 1843k    0     0  1843k      0  0:00:01  0:00:01 --:--:-- 3080k
        1 file(s) moved.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   652  100   652    0     0    652      0  0:00:01 --:--:--  0:00:01  1738
100 4774k  100 4774k    0     0  2387k      0  0:00:02  0:00:02 --:--:-- 6254k
        1 file(s) moved.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   655  100   655    0     0    655      0  0:00:01 --:--:--  0:00:01  1824
100 4732k  100 4732k    0     0  2366k      0  0:00:02  0:00:02 --:--:-- 5031k
        1 file(s) moved.
```

Please suggest what may be causing this?

Thank you

**Comment by farazk86** [comment]
I managed to fix this,

for anyone else having this problem, it was related to the labels txt file being loaded.

My labels.txt file was in ``ANSI`` encoding whereas the required is ``UTF-8``. Saving it in correct encoding fixed this error.

such a simple mistake and 2 days wasted =/
