### ISSUE TITLE
Can't run app on iOS

### ISSUE THREAD

**Issue by Grumpy-Kat** [am15h/tflite_flutter_plugin#67]
I'm having an issue building for iOS. When I run "pod install", I get the error:
`-> Installing tflite_flutter (0.1.0)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has frameworks with conflicting names: tensorflowlitec.framework.

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/target_validator.rb:67:in
    `verify_no_duplicate_names'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/target_validator.rb:54:in
    `block (2 levels) in verify_no_duplicate_framework_and_library_names'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/target_validator.rb:48:in
    `each_key'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/target_validator.rb:48:in
    `block in verify_no_duplicate_framework_and_library_names'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/target_validator.rb:47:in
    `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/target_validator.rb:47:in
    `verify_no_duplicate_framework_and_library_names'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/target_validator.rb:37:in
    `validate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:595:in `validate_targets'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:162:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'`

**Comment by am15h** [comment]
@Grumpy-Kat Is your problem related to issue https://github.com/am15h/tflite_flutter_plugin/issues/48

**Comment by espbee** [comment]
@Grumpy-Kat random thought-- I was getting the same error until I realized I was also including the tflite library in my app-- as opposed to tflite_flutter ... when i removed the former, all was well--

**Comment by twbabyduck** [comment]
@espbee Hi
Did you solve this issue? I know how to modify podspec to able to compile https://pub.dev/packages/tflite and https://pub.dev/packages/tflite in one project. However, I will get this error message "Unhandled Exception: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, TfLiteModelCreate): symbol not found)".

Thanks

Related issue: https://github.com/am15h/tflite_flutter_plugin/issues/88

**Comment by AhmedMahhmoud** [comment]
> @Grumpy-Kat random thought-- I was getting the same error until I realized I was also including the tflite library in my app-- as opposed to tflite_flutter ... when i removed the former, all was well--

is there a way i can use both in my app ? how to do that please?

**Comment by twbabyduck** [comment]
@AhmedMahhmoud check #88 I had modified some setting files but I think is not the right way to do it.
but you can at least test it in debug mode. As for release mode I think you will meet the same problem that I currently have now.

**Comment by espbee** [comment]
@twbabyduck i actually didn't need both-- was just a typo for me. good luck with your situation though. i'll bet that whatever you're doing with the old library you can do with the new one though-- albeit with some more legwork---- idk, good luck

**Comment by Mmisiek** [comment]
I have this issue,  I include in pubspec.yaml:
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.0

and I can't run on iOS but I can run on Android.
Please help !

**Comment by Mmisiek** [comment]
I have framework in both locations, still does not compile

**Comment by supratikkoley** [comment]
I am also facing the saming issue.
