### ISSUE TITLE
Unable to use custom models from teachable machine

### ISSUE THREAD

**Issue by LokieVikky** [am15h/tflite_flutter_plugin#92]
I just replaced the assets in your object detection project with the model exported from teachable machine -tflite floating point model

Syncing files to device Pixel 4a...
I/CameraManagerGlobal( 9134): Connecting to camera service
I/tflite  ( 9134): Initialized TensorFlow Lite runtime.
W/Gralloc4( 9134): allocator 3.x is not supported
E/flutter ( 9134): [ERROR:flutter/runtime/dart_isolate.cc(882)] Unhandled exception:
E/flutter ( 9134): RangeError (index): Invalid value: Only valid value is 0: 1
E/flutter ( 9134): #0      List.[] (dart:core-patch/growable_array.dart:177:60)
E/flutter ( 9134): #1      Classifier.predict (package:object_detection/tflite/classifier.dart:118:65)
E/flutter ( 9134): #2      IsolateUtils.entryPoint (package:object_detection/utils/isolate_utils.dart:45:51)
E/flutter ( 9134): #3      _RootZone.runUnary (dart:async/zone.dart:1450:54)
E/flutter ( 9134): #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 9134): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 9134): #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 9134): #7      Future._complete (dart:async/future_impl.dart:519:7)
E/flutter ( 9134): #8      _StreamIterator._onData (dart:async/stream_impl.dart:1070:20)
E/flutter ( 9134): #9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
E/flutter ( 9134): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter ( 9134): #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter ( 9134): #12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
E/flutter ( 9134): #13     _StreamController._add (dart:async/stream_controller.dart:682:7)
E/flutter ( 9134): #14     _StreamController.add (dart:async/stream_controller.dart:624:5)
E/flutter ( 9134): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
W/System  ( 9134): A resource failed to call release.

**Comment by am15h** [comment]
Can you share some reproducible code?

**Comment by am15h** [comment]
Closing due to inactivity, please feel free to re-open.
