### ISSUE TITLE
Plugin crashes on android 4.1

### ISSUE THREAD

**Issue by CaptainDario** [am15h/tflite_flutter_plugin#95]
When I try to run this plugin on an emulator with android 4.1 (`flutter run --enable-software-rendering` otherwise the emulators won't work with flutter) I get the following error:

```{bash}
E/flutter ( 1947): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (Cannot load library: load_library[1093]: Library 'libtensorflowlite_c.so' not found)
E/flutter ( 1947): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
E/flutter ( 1947): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
E/flutter ( 1947): #2      tflitelib.<anonymous closure> (package:tflite_flutter/src/bindings/dlib.dart:8:27)
E/flutter ( 1947): #3      tflitelib (package:tflite_flutter/src/bindings/dlib.dart:12:2)
E/flutter ( 1947): #4      tflitelib (package:tflite_flutter/src/bindings/dlib.dart)
E/flutter ( 1947): #5      tfLiteModelCreateFromBuffer (package:tflite_flutter/src/bindings/model.dart:10:35)
E/flutter ( 1947): #6      tfLiteModelCreateFromBuffer (package:tflite_flutter/src/bindings/model.dart)
E/flutter ( 1947): #7      new Model.fromBuffer (package:tflite_flutter/src/model.dart:36:19)
E/flutter ( 1947): #8      new Interpreter.fromBuffer (package:tflite_flutter/src/interpreter.dart:90:25)
E/flutter ( 1947): #9      Interpreter.fromAsset (package:tflite_flutter/src/interpreter.dart:114:24)
E/flutter ( 1947): <asynchronous suspension>
E/flutter ( 1947): #10     initInterpreterFallback (package:da_kanji_recognizer_mobile/initInterpreter.dart:100:10)
E/flutter ( 1947): <asynchronous suspension>
E/flutter ( 1947): #11     initInterpreterAndroid (package:da_kanji_recognizer_mobile/initInterpreter.dart:49:19)
E/flutter ( 1947): <asynchronous suspension>
E/flutter ( 1947): #12     init (package:da_kanji_recognizer_mobile/main.dart:42:34)
E/flutter ( 1947): <asynchronous suspension>
E/flutter ( 1947): #13     main (package:da_kanji_recognizer_mobile/main.dart:19:3)
E/flutter ( 1947): <asynchronous suspension>
E/flutter ( 1947):
```

Is there a workaround available for this?
A user of my app reported this behavior therefore it would be nice to solve.

Edit: looks like it is connect to flutter/flutter#73318

**Comment by am15h** [comment]
This is a known issue with ffi, which is currently being tracked with https://github.com/flutter/flutter/issues/59834

**Comment by CaptainDario** [comment]
[here](https://github.com/flutter/flutter/issues/73318#issuecomment-754598119) is a workaround given. However I am not sure how to implement it.
Do you have any advice how to do that?

**Comment by am15h** [comment]
I am not sure if this workaround could cause any side-effects, so I would suggest you fork this repo and replace [this file](https://github.com/am15h/tflite_flutter_plugin/blob/master/android/src/main/java/com/tfliteflutter/tflite_flutter_plugin/TfliteFlutterPlugin.java
) with the code below.

```java
package com.tfliteflutter.tflite_flutter_plugin;

import androidx.annotation.NonNull;
import io.flutter.embedding.engine.plugins.FlutterPlugin;
import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel;
import io.flutter.plugin.common.MethodChannel.MethodCallHandler;
import io.flutter.plugin.common.MethodChannel.Result;
import io.flutter.plugin.common.PluginRegistry.Registrar;

/** TfliteFlutterPlugin */
public class TfliteFlutterPlugin implements FlutterPlugin, MethodCallHandler {
  @Override
  public void onAttachedToEngine(@NonNull FlutterPluginBinding flutterPluginBinding) {
    final MethodChannel channel = new MethodChannel(flutterPluginBinding.getFlutterEngine().getDartExecutor(), "tflite_flutter_plugin");
    channel.setMethodCallHandler(new TfliteFlutterPlugin());
    loadLibrary();
  }

  // This static function is optional and equivalent to onAttachedToEngine. It supports the old
  // pre-Flutter-1.12 Android projects. You are encouraged to continue supporting
  // plugin registration via this function while apps migrate to use the new Android APIs
  // post-flutter-1.12 via https://flutter.dev/go/android-project-migration.
  //
  // It is encouraged to share logic between onAttachedToEngine and registerWith to keep
  // them functionally equivalent. Only one of onAttachedToEngine or registerWith will be called
  // depending on the user's project. onAttachedToEngine or registerWith must both be defined
  // in the same class.
  public static void registerWith(Registrar registrar) {
    final MethodChannel channel = new MethodChannel(registrar.messenger(), "tflite_flutter_plugin");
    channel.setMethodCallHandler(new TfliteFlutterPlugin());    
  }

  @Override
  public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
    if (call.method.equals("getPlatformVersion")) {
      result.success("Android " + android.os.Build.VERSION.RELEASE);
    } else {
      result.notImplemented();
    }
  }

  @Override
  public void onDetachedFromEngine(@NonNull FlutterPluginBinding binding) {
  }

  private static boolean isLibraryLoaded = false;

  private static void loadLibrary() {
    if (isLibraryLoaded) {
      return;
    }

    // Loads `libX.so`.
    System.loadLibrary("X");
    isLibraryLoaded = true;
  }
}

```

**Comment by CaptainDario** [comment]
Thank you very much for your help!
I will try this out tomorrow and report here.

**Comment by CaptainDario** [comment]
Sadly I am still hitting the same error.

I forked this repository (trying on the most recent branch) and replaced the content of [this file](https://github.com/am15h/tflite_flutter_plugin/blob/master/android/src/main/java/com/tfliteflutter/tflite_flutter_plugin/TfliteFlutterPlugin.java)
with 
```java
package com.tfliteflutter.tflite_flutter_plugin;

import androidx.annotation.NonNull;
import io.flutter.embedding.engine.plugins.FlutterPlugin;
import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel;
import io.flutter.plugin.common.MethodChannel.MethodCallHandler;
import io.flutter.plugin.common.MethodChannel.Result;
import io.flutter.plugin.common.PluginRegistry.Registrar;

/** TfliteFlutterPlugin */
public class TfliteFlutterPlugin implements FlutterPlugin, MethodCallHandler {
  @Override
  public void onAttachedToEngine(@NonNull FlutterPluginBinding flutterPluginBinding) {
    final MethodChannel channel = new MethodChannel(flutterPluginBinding.getFlutterEngine().getDartExecutor(), "tflite_flutter_plugin");
    channel.setMethodCallHandler(new TfliteFlutterPlugin());
    loadLibrary();
  }

  // This static function is optional and equivalent to onAttachedToEngine. It supports the old
  // pre-Flutter-1.12 Android projects. You are encouraged to continue supporting
  // plugin registration via this function while apps migrate to use the new Android APIs
  // post-flutter-1.12 via https://flutter.dev/go/android-project-migration.
  //
  // It is encouraged to share logic between onAttachedToEngine and registerWith to keep
  // them functionally equivalent. Only one of onAttachedToEngine or registerWith will be called
  // depending on the user's project. onAttachedToEngine or registerWith must both be defined
  // in the same class.
  public static void registerWith(Registrar registrar) {
    final MethodChannel channel = new MethodChannel(registrar.messenger(), "tflite_flutter_plugin");
    channel.setMethodCallHandler(new TfliteFlutterPlugin());    
  }

  @Override
  public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
    if (call.method.equals("getPlatformVersion")) {
      result.success("Android " + android.os.Build.VERSION.RELEASE);
    } else {
      result.notImplemented();
    }
  }

  @Override
  public void onDetachedFromEngine(@NonNull FlutterPluginBinding binding) {
  }

  private static boolean isLibraryLoaded = false;

  private static void loadLibrary() {
    if (isLibraryLoaded) {
      return;
    }

    // Loads `libX.so`.
    System.loadLibrary("libtensorflowlite_c");
    isLibraryLoaded = true;
  }
}
```

Than in my pubspec I referenced it with:
```yaml
...
dependencies:
  tflite_flutter:
    path: ../tflite_flutter_plugin
...
```

I still get:
```bash
E/flutter ( 2644): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (Cannot load library: load_library[1093]: Library 'libtensorflowlite_c.so' not found)
E/flutter ( 2644): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
E/flutter ( 2644): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
E/flutter ( 2644): #2      tflitelib.<anonymous closure> (package:tflite_flutter/src/bindings/dlib.dart:9:27)
E/flutter ( 2644): #3      tflitelib (package:tflite_flutter/src/bindings/dlib.dart:13:2)
E/flutter ( 2644): #4      tflitelib (package:tflite_flutter/src/bindings/dlib.dart)
E/flutter ( 2644): #5      tfLiteModelCreateFromBuffer (package:tflite_flutter/src/bindings/model.dart:10:35)
E/flutter ( 2644): #6      tfLiteModelCreateFromBuffer (package:tflite_flutter/src/bindings/model.dart)
E/flutter ( 2644): #7      new Model.fromBuffer (package:tflite_flutter/src/model.dart:36:19)
E/flutter ( 2644): #8      new Interpreter.fromBuffer (package:tflite_flutter/src/interpreter.dart:94:25)
E/flutter ( 2644): #9      Interpreter.fromAsset (package:tflite_flutter/src/interpreter.dart:119:24)
E/flutter ( 2644): <asynchronous suspension>
E/flutter ( 2644): #10     initInterpreterFallback (package:da_kanji_recognizer_mobile/initInterpreter.dart:100:10)
E/flutter ( 2644): <asynchronous suspension>
E/flutter ( 2644): #11     initInterpreterAndroid (package:da_kanji_recognizer_mobile/initInterpreter.dart:49:19)
E/flutter ( 2644): <asynchronous suspension>
E/flutter ( 2644): #12     init (package:da_kanji_recognizer_mobile/main.dart:40:34)
E/flutter ( 2644): <asynchronous suspension>
E/flutter ( 2644): #13     main (package:da_kanji_recognizer_mobile/main.dart:21:3)
E/flutter ( 2644): <asynchronous suspension>
E/flutter ( 2644):
```

Any idea what I am missing?

**Comment by CaptainDario** [comment]
I am trying on an emulator with those settings:
* android 4.1 (x86)
* Software - GLES 1.1 
* 2 CPU cores
* 512 MB RAM

**Comment by am15h** [comment]
@CaptainDario Thanks for transferring this to the flutter repository. https://github.com/flutter/flutter/issues/59834#issuecomment-809207169.  I am closing this issue from here.
